### ISSUE TITLE
tex capacity exceeded ... input levels for 1000+ citations

### ISSUE THREAD

**Issue by Derek-Jones** [ho-tex/hyperref#30] opened 2017-02-18 16:16 UTC
I am working on a book which currently contains 1000+ citations.

When backref=page is enabled I get the dreaded "tex capacity exceeded" error (increasing the file limit has no effect).  Everything works fine if this option is commented out.

Everything works ok for a subset of thebook that only contains 600 citations:
http://shape-of-code.coding-guidelines.com/2017/01/29/empirical-software-engineering-using-r-first-draft-available-for-download/

Does hyperref has an internal limit (perhaps an implicit assumption) on the number of citations?  Any suggestions for increasing the number of supported citations?

**Comment by davidcarlisle** [comment] 2017-02-18 16:40
The limit won't be explicit in hyperrref, it's just hitting a system level limit. It's usually possible to re-arrange recursive calls not to nest so deeply but I'm not sure what's happening here. Could you confirm if it is the number of distinct citations that's the issue or the fact that the longer document has more instances of a single citation (so the back reference list for that citation is getting too long)

**Comment by davidcarlisle** [comment] 2017-02-18 16:52
you said increasing the limit has no effect, which limit did you increase? If I read the fragment of error message correctly then you want to increase

`stack_size = 5000       % simultaneous input sources`


(in /usr/local/texlive/2016/texmf-dist/web2c/texmf.cnf or equivalent location)

**Comment by Derek-Jones** [comment] 2017-02-18 17:13
Adding the following to texmf.cnf
max_in_open = 20
stack_size = 10000

Just changes the numbers in the final report.  The following is the end of the log file:

[366<./hujics-proc-pita.pdf>] (./rbook.bbl (./rbook.brf (./rbook.brf (./rbook.b
rf (./rbook.brf (./rbook.brf (./rbook.brf (./rbook.brf (./rbook.brf (./rbook.br 
f (./rbook.brf (./rbook.brf (./rbook.brf (./rbook.brf (./rbook.brf (./rbook.brf
(./rbook.brf (./rbook.brf (./rbook.brf
! TeX capacity exceeded, sorry [text input levels=20].
\@filef@und ->rbook.brf  

l.1 \backcite {Triplett_03}{{1}{1}{chapter.1}}

If you really absolutely need more capacity,
you can ask a wizard to enlarge me.

Here is how much of LuaTeX's memory you used:
 36897 strings out of 494693
 195437,1373583 words of node,token memory allocated 12111 words of node memory still in use:
   85 hlist, 20 vlist, 22 rule, 29 disc, 16 math, 192 glue, 22 kern, 47 penalty,
 564 glyph, 118 glue_spec, 12 action, 20 if_stack, 1 shape, 14 write, 16 local_p
ar, 1 dir, 4 pdf_refximage, 8 pdf_start_link, 8 pdf_end_link, 4 pdf_dest, 34 pdf
_colorstack, 3 pdf_setmatrix, 3 pdf_save, 3 pdf_restore nodes
   avail lists: 2:16,3:5344,4:4368,5:6620,6:6762,7:1521,8:67,9:4334,10:608
 32131 multiletter control sequences out of 65536+600000
 235 fonts using 9235991 bytes
 167i,18n,95p,2027b,1575s stack positions out of 10000i,500n,10000p,200000b,100000s
!  ==> Fatal error occurred, no output PDF file produced!

The Triplett citation is the first line in the brf file (which has 1584 entries).  Some of the entries are malformed in that the citation is the title of the paper (which has yet to be integrated into the material):

\backcite {Triplett_03}{{1}{1}{chapter.1}}

\backcite {Slade_07}{{3}{1.1}{figure.caption.7}}
\backcite {Zhang_01}{{3}{1.1}{figure.caption.7}}
\backcite {A Spectral Analysis of World GDP Dynamics: Kondratieff Waves, Kuznets Swings}{{3}{1.1}{figure.caption.7}}
\backcite {Hayes_01}{{4}{1.1.1}{subsection.1.1.1}}
\backcite {Ware_60}{{4}{1.1.1}{subsection.1.1.1}}

**Comment by davidcarlisle** [comment] 2017-02-18 17:37
why it inputting the book.br over and over again but that's hitting a list of 20 input levels as you have set this to 20

max_in_open = 15        % simultaneous input files and error insertions, 


I wrote that code last century but as far as I can see it's only supposed to input the file once.

/rbook.bbl (./rbook.brf (./rbook.brf (./rbook.b
rf (./rbook.brf (./rbook.brf (./rbook.brf (./rbook.brf (./rbook.brf (./rbook.br
f (./rbook.brf (./rbook.brf (./rbook.brf (./rbook.brf (./rbook.brf (./rbook.brf
(./rbook.brf (./rbook.brf (./rbook.brf

looks bad and like an infinite loop so increasing the limit won't help.

I'm not sure I understood your "malformed" comment but I suspect that whatever you mean, you are causing backref to loop

**Comment by Derek-Jones** [comment] 2017-02-18 18:08
\backcite {A Spectral Analysis of World GDP Dynamics: Kondratieff Waves, Kuznets Swings}{{3}{1.1}{figure.caption.7}}

is an example of a "malformed" entry. The characters between the first pair of {} is the title of the paper and this appears in a \cite.  There is no corresponding entry in the the bibtext file.

This particular entry is not causing a problem (it occurs in the draft material posted on the web).

There may be another "malformed" entry later on causing the problem.  All of these entries will all eventually go away.

I will let you know if the problem persists once all the citations are as they should be.

**Comment by davidcarlisle** [comment] 2017-03-16 23:20
OK I'm closing this now, please re-open if there seems to be  reproducible issue

**Closed by davidcarlisle** 2017-03-16 23:20 UTC

**Comment by davidcarlisle** [comment] 2018-08-01 09:05
sorry I do not understand your example. If I extend the fragment you posted to a document like

```
\documentclass{report}

% for the C++ macro
\usepackage{texlogos}

\begin{document}

% -------
% Chapter
% -------

\chapter{Source code}

method

\cite{An empirical study on the actual use of \cpluspluslogo\xspace templates}

How
\end{document}

```

then you get an error

`! Argument of \@firstofone has an extra }.`

which is just a more or less random error as the argument of `\cite`  has to expand to just characters (to make the csname to look up the citation key).

Depending on the use case

`\cite{An empirical study on the actual use of \string\cpluspluslogo\string\xspace templates}`

runs without error although of course neither `\cpluspluslogo` nor `\xspace` are really used at all in that case.

**Comment by Derek-Jones** [comment] 2018-08-01 11:37
I got rather carried away stripping things down to the basics.
Some of the packages are probably not needed.

Try the latex below.  You will also need to supply a body.bbl (otherwise there is no problem).

The first run through works, it's the second run when the failure occurs.



\documentclass[a4paper,english]{book}

\usepackage[T1]{fontenc}
\usepackage[main=english]{babel}

\usepackage[latin1]{luainputenc}
\usepackage{times}
% \usepackage[scaled=0.85]{luximono}

\usepackage{acronym}
\usepackage{afterpage}
\usepackage[allowmove]{url}
\usepackage{alltt}
\usepackage{booktabs}
\usepackage{calc}
\usepackage[margin=10pt,
        font=footnotesize,
        labelfont=bf,
        tableposition=top]{caption}
\usepackage[outerbars]{changebar}
\usepackage[strict]{changepage}
\usepackage{color}
\usepackage{ellipsis}
\usepackage{fancyvrb}
\CustomVerbatimEnvironment{CodeVerbatim}{Verbatim}{numbers=left, samepage=false}
\usepackage{float}
% Before hyperlink to have consistent links to footnotes
\usepackage{footmisc}
\usepackage{framed}
\usepackage[verbose=false,
                top=1.2cm, bottom=2.0cm,
                inner=1cm, outer=7cm,
                marginparwidth=6.5cm]{geometry}
\usepackage{fancybox}
\usepackage{ifthen}
\usepackage{graphicx}
% maths support
\usepackage{mathrsfs}
\usepackage{amsmath}
\usepackage{amssymb}
\DeclareMathOperator\sech{sech}
% Since mathptmx is included the following symbols are saved to prevent
% from a clash, even if the symbols actually appear as black boxes...
%
\let\stdcoprod=\coprod
\let\stdamalg=\amalg
\let\stdjmath=\jmath
\usepackage{mathptmx}
\let\coprod=\stdcoprod
\let\amalg=\stdamalg
\let\jmath=\stdjmath

\usepackage{moredefs,lips}
\usepackage{makeidx}
%\usepackage{microtype}
%\usepackage{mparhack}
\usepackage{multicol}
\usepackage[autolanguage]{numprint}
\usepackage{placeins}
\usepackage{ragged2e}
\usepackage{shadow}
% \usepackage{marginfix} % stop sidenotes dropping off the end of a page
\usepackage{sidenotes}
%\usepackage{tabularx}
\usepackage{pifont}   % various symbols
\usepackage{textcomp} % text-like symbols
% for the C++ macro
\usepackage{texlogos}
\usepackage[allowmove]{url}
\usepackage{breakurl}
\def\UrlBreaks{\do\/\do-}

%\usepackage{wasysym}
\usepackage{xspace}


\usepackage[pdftex,
	plainpages=false,
 	pdfpagelabels=true, %
 	backref=page,       %
	breaklinks=true,
 	colorlinks=true,
	citecolor=blue,
 	linktocpage=true,
	pdfstartview=FitH,
%  	debug=true,
 	pdfauthor={Derek M. Jones},
	pdftitle={Evidence-based Software Engineering using R},%
 	pdfkeywords={Empirical,Evidence based,Software Engineering,R,Statistics,data,data analysis},
	pdfcreator={lualatex, via dblatex, via asciidoc},%
 	bookmarks=true]{hyperref}    % package documentation suggests that this be the last usepackage

\usepackage{texlinks}

\usepackage{bookmark}

\usepackage[superscript]{cite}


% \bibliographystyle{abbrv}
\bibliographystyle{xabbrv}

\setcounter{tocdepth}{5}
\setcounter{secnumdepth}{5}
\title{Evidence-based Software Engineering using R}
\author{Derek M. Jones}
\hypersetup{%
pdfcreator={lualatex, via dblatex, via asciidoc},%
pdftitle={Evidence-based Software Engineering using R},%
pdfauthor={Derek M. Jones},%
}

\makeindex
\makeglossary

% \setkeys{Gin}{width=\linewidth,totalheight=\textheight,keepaspectratio}
\graphicspath{{graphics/}}

\begin{document}
% ------- 
% Chapter 
% ------- 

\chapter{Source code}
\label{_source_code}\hyperlabel{_source_code}%

method

\cite{An empirical study on the actual use of \cpluspluslogo\xspace templates}

How

\bibliography{body}

\end{document}

**Comment by davidcarlisle** [comment] 2018-08-01 12:24
the new  test file gives several errors in tl2018, the first few being
```

! LaTeX Error: Command \float@end already defined.
               Or name \end... illegal, see p.192 of the manual.

! LaTeX Error: Command \float@dblend already defined.
               Or name \end... illegal, see p.192 of the manual.
! Undefined control sequence.
l.123 \label{_source_code}\hyperlabel
                                     {_source_code}%
? 
```

However even if the package loading is fixed to address them I think  backref will still fall over. However  I think I would still class this as user-error. I don't think it is unreasonable for hyperref/backref to only support `\cite` usage that is legal. As shown in the small example [above](https://github.com/ho-tex/hyperref/issues/30#issuecomment-409505798) using non expandable macros is an error, loading hyperref has made it fail in a slightly different place but it is bound to fail somewhere.

**Comment by Derek-Jones** [comment] 2018-08-01 12:35
Once I saw what was causing the problem I realised it was a user error.  Another case of hard to track down problem in latex.

I posted here again to provide closure.
