### ISSUE TITLE
Wrong hyperlinks in TOC with titletoc

### ISSUE THREAD

**Issue by jbezos** [ho-tex/hyperref#86] opened 2019-02-24 17:55 UTC
It seems `hyperref` redefines a macro in `titletoc` in the wrong way. Consider the following example
```
\documentclass{article}

\usepackage{titlesec}

\usepackage{hyperref}

\usepackage{titletoc}

\titlecontents*{subsection}[1.8pc]
  {\small}
  {\thecontentslabel. }
  {}
  {, \thecontentspage}
  [.---][.]

\begin{document}

\tableofcontents

text\newpage\section   {section.1}{Introduction}{}% 1

text\newpage\section   {section.2}{Quick Reference}{}% 2

text\newpage\subsection{subsection.2.1}{Format}{section.2}% 3

text\newpage\section   {section.3}{Advanced Interface}{}% 7

text\newpage\subsection{subsection.3.1}{Format}{section.3}% 8

\end{document}
```
The link for section 3 in the TOC sends you to subsection 2.1.  The problem seems to be in the line:
```
\def\noexpand\Hy@tocdestname{#4}%
```
If the definition is global then the link is correct:
```
\gdef\noexpand\Hy@tocdestname{#4}%
```

**Comment by u-fischer** [comment] 2019-02-25 23:41
Imho the problem is in titletoc. It opens a group somewhere (I think in the processing of the subsection entry) and then closes this group in the middle of `\l@section` with `\contentsfinish` and so looses the correct value of `Hy@tocdestname` before the link has been created:

~~~~

\l@section ->\ttl@lselect {section}

\ttl@lselect #1->\ifnum \csname ttll@#1\endcsname >\c@tocdepth \else \contentsfinish \fi \ifnum \csname ttll@#1\endcsname <\ttl@toctop \relax \expandafter \@gobbletwo \else \expandafter \expandafter \csname ttl@savel@#1\endcsname \fi 
#1<-section

\ttll@section ->1

\contentsfinish ->\ifttl@fromblock \xdef \ttl@b {-10000}\ttl@preend \@@par \endgroup %<----- here
\global \ttl@fromblockfalse \fi 
~~~~

(`\ifttl@fromblock` is true for section 3.

I don't think that making `\Hy@tocdestname` global is the right fix.

**Comment by jbezos** [comment] 2019-02-26 14:45
Sure it opens a group. It's necessary for entries to be grouped and formatted in a single paragraph. Very likely making `\Hy@tocdestname `is not the right fix, but it's a `hyperref` declaration, which is not under the control of `titletoc`.

**Comment by jbezos** [comment] 2019-02-26 15:22
Well, I'll fix it with:
```
\def\contentsfinish{%
  \ifttl@fromblock
    \xdef\ttl@b{-10000}% ships out any saved punctuation
    \ttl@preend
    \@@par
    \ifx\Hy@tocdestname\@undefined
      \endgroup
    \else
      \edef\ttl@aftergroup{%
        \endgroup
        \def\noexpand\Hy@tocdestname{\Hy@tocdestname}}%
      \ttl@aftergroup
    \fi
    \global\ttl@fromblockfalse
  \fi}
```
But I still think groups inside a toc file is not intrinsically wrong and `hyperref` should consider this possibility.

**Comment by u-fischer** [comment] 2019-02-26 15:27
What I mean is that you are adding groups across commands. hyperref basically redefines \contentsline to do

      \def\Hy@tocdestname{something} \l@section{ content with \Hy@tocdestname }{...} 

and you are closing the group in l@section before the content is actually processed. We can't use \aftergroup to smuggle the command out, as other definitions of \l@section don't have this group, and making the command global looks imho suspicious. So some other solution is needed.

**Comment by u-fischer** [comment] 2019-02-26 15:46
I don't think that groups are wrong, but the idea to open one in one contentsline and close it in the middle of the next, is rather curious. One solution could be that hyperref expands `\Hy@tocdestname` before passing it to l@section,

**Comment by jbezos** [comment] 2019-02-26 15:56
There is an explanation. This one of these cases where the format of an
element is not known on beforehand, because it depends of the following
element. And also, the only reliable way to restore a "text state" (color,
size, and so on) is with a group.

**Closed** 2019-03-01 14:30 UTC
